// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InputUser struct {
	Username string `json:"username"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type UserData struct {
	Username string `json:"username"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type UserRequest struct {
	Username string `json:"username"`
	FullName string `json:"fullName"`
	Email    string `json:"email"`
}

type UserResponse struct {
	Users []*UserData `json:"users"`
	User  *UserData   `json:"user"`
}
